6장 DML
select *
from dept2;

insert into dept2(dcode, dname, pdept)
values (9002, 'temp_3', 1006);

alter session set nls_date_format='rrrr=mm=dd:hh24:mi:ss';

INSERT INTO PROFESSOR (PROFNO, NAME, ID, POSITION, PAY, HIREDATE)
VALUES (5001, 'JAMES BOND', 'LOVE ME', 'A FULL PROFESSOR', 500, '2014-10-23');

SELECT *
FROM PROFESSOR;
--
CREATE TABLE T_MINUS(
NO1 NUMBER,
NO2 NUMBER(3),
NO3 NUMBER(3,2));

SELECT * FROM T_MINUS;

INSERT INTO  T_MINUS VALUES(1, 1, 1);
INSERT INTO  T_MINUS VALUES(1.1, 1.1, 1.1);
INSERT INTO  T_MINUS VALUES(-1.1, -1.1, -1.1);
--
CREATE TABLE PROFRSSOR3
AS
SELECT * FROM PROFESSOR
WHERE 1=2;

SELECT * FROM PROFESSOR3;

INSERT INTO PROFRSSOR3
SELECT * FROM PROFESSOR;
--
CREATE TABLE PROFESSOR4
AS
SELECT PROFNO, NAME, PAY
FROM PROFESSOR
WHERE 1=2;

INSERT INTO PROFESSOR4
SELECT PROFNO, NAME, PAY
FROM PROFESSOR
WHERE PROFNO > 4000;

SELECT * FROM PROFESSOR4;
--
create table prof_3
(profno number,
name varchar2(25));

create table prof_4
(profno number,
name varchar2(25));

SELECT * FROM PROFESSOR;

INSERT ALL
WHEN PROFNO BETWEEN 1000AND 1999 THEN
INTO PROF_3 VALUES(PROFNO, NAME)
WHEN PROFNO BETWEEN 2000 AND 2999 THEN
INTO PROF_4 VALUES(PROFNO, NAME)
SELECT PROFNO, NAME
FROM PROFESSOR ;

SELECT * FROM PROF_3;
SELECT * FROM PROF_4;

ROLLBACK;

TRUNCATE TABLE PROF_3;
TRUNCATE TABLE PROF_4;

INSERT ALL
INTO PROF_3 VALUES (PROFNO, NAME)
INTO PROF_4 VALUES (PROFNO, NAME)
SELECT PROFNO, NAME
FROM PROFESSOR
WHERE PROFNO BETWEEN 3000 AND 3999;






--20200402  오후 
--10장 서브쿼리
SELECT *
FROM EMP
WHERE SAL = 2975 OR SAL = 2850 OR SAL = 2450;
--OR IN 같은 결과 가져올 수 있음
SELECT *
FROM EMP
WHERE SAL IN (2975, 2850, 2450);

SELECT ENAME, COMM
FROM EMP
WHERE COMM<
(SELECT COMM
FROM EMP
WHERE ENAME = 'WARD');
--단일행 서브쿼리
SELECT S.NAME, D.DNAME
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO1 = D.DEPTNO
AND S.DEPTNO1 = (SELECT DEPTNO1 
FROM STUDENT
WHERE NAME = '이윤나');

SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;

SELECT
FROM PROFESSOR P, DEPARTMENT D
